workflows:
  react-native:
    name: React Native App
    max_build_duration: 120
    environment:
      vars:
        XCODE_WORKSPACE: "{{ ADD_WORKSPACE_NAME_HERE }}"
        XCODE_SCHEME: "{{ Movie_App }}"
        node: latest
    scripts:
      - npm install
      - echo "sdk.dir=$HOME/programs/android-sdk-macosx"> "$FCI_BUILD_DIR/android/local.properties"
      - | 
          # build Android
          cd android && chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
 